# Generated by Django 4.0.1 on 2022-01-24 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='category',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='main.coursecategory'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='creator',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
