# Generated by Django 4.0 on 2022-02-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transactionhistory_remove_account_gender_account_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='courses_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='courses_enrolled',
            field=models.IntegerField(default=0),
        ),
    ]
