# Generated by Django 4.0 on 2022-02-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_courses_created_account_courses_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/course_thumbnail/'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='used_techs',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
