# Generated by Django 4.0 on 2022-02-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_coursecategory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourseprogress',
            options={'verbose_name_plural': '5. course_progress'},
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('no', models.IntegerField()),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='chapter_videos')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursedetails')),
            ],
            options={
                'verbose_name_plural': '4. chapters',
            },
        ),
    ]
